MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # RPN:
  #   PRE_NMS_TOP_N_TEST: 6000
  #   POST_NMS_TOP_N_TEST: 1000
  RPN:
    PRE_NMS_TOP_N_TEST: 3000
    POST_NMS_TOP_N_TEST: 500
  DEVICE: "cpu"
DATASETS:
  # TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  # TEST: ("coco_2014_minival",)
  TRAIN: ("coco_post_train", "coco_post_val")
  TEST: ("coco_post_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
OUTPUT_DIR: "./runs/20190515"
# OUTPUT_DIR: "./runs"
